### ISSUE TITLE
Do not print info message about file creation in case of error

### ISSUE THREAD

**Issue by valdemar1977** [lovasoa/dezoomify-py#2]
Hello!
Is it possible do not add a INFO: Dezoomified image create... in case of error (in fact in any case when file is not created)?
At the moment when read log file after batch downloading this message sometimes confuse.

**Comment by valdemar1977** [comment]
By the way may be made some changes in output log formatting?
It will be more readable.
I'm delete start tabs in self.log.debug (lines 636-642)
and change Downloading to Loading (lines 264 and 302)

![2016-05-05_13-47-46](https://cloud.githubusercontent.com/assets/19201704/15041900/38ce98a2-12c8-11e6-8161-3d8fd98ebfc0.png)

**Comment by lovasoa** [comment]
You should make a pull request! I'll merge it!
