### ISSUE TITLE
Possibility to create list of not downloaded files

### ISSUE THREAD

**Issue by valdemar1977** [lovasoa/dezoomify-py#4]
Т.е. создавать файл содержащий линки и имена (как во входном файле) проблемных загрузок. Его можно сразу потом подавать на вход при повторных попытках скачивания.
### translation

I.e. create a file containing the URLs and names of the failed downloads (as in the input file). You could then use this file as input on your next try.

**Comment by lovasoa** [comment]
Thanks for the suggestion.

**Comment by valdemar1977** [comment]
Спасибо огромное!!!
Если позволите не большое замечание, можно записывать не полное имя файла с путем, а только короткое (имя_файла.jpg). Иначе при подаче этого файла на вход dezoomify, не будет возможности указать куда писать файлы. Программа игнорирует выходную директорию указанную в командной строке т.к. в файле указан полный путь к файлу.
